import Link from "next/link";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} bg-slate-900 text-slate-100 h-screen`}
      >
        <nav className="w-full bg-slate-800 border-b border-slate-600 h-16 flex items-center">
          <div className="flex justify-between container mx-auto">
            App Name
            <ul className="flex gap-2">
              <li>
                <Link href={"/"}>Home</Link>
              </li>
              <li>
                <Link href={"/about"}>About</Link>
              </li>
            </ul>
          </div>
        </nav>
        <main className="py-12">{children}</main>
      </body>
    </html>
  );
}
